### ISSUE TITLE
Hot Reload の検討

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#13]
realize というライブラリで watch が実現できるようなので，余力あれば対応したい．

https://qiita.com/enta0701/items/9f60ad18600acab8c93d

こちらのほうがやりたいことに近いかもしれません．

Go + echo + Docker + VSCode + Remote Containers で開発環境の構築
https://qiita.com/f_sugar/items/49871913fb4baf1ad8d2

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
