### ISSUE TITLE
READMEにgoenv含めた開発環境のインストール手順を記載する

### ISSUE THREAD

**Issue by hapoon** [hapoon/go-api-template#15]
チーム開発するにあたり、実行バージョンの統一をした方が良いので `goenv` でのgoバージョン管理を行う。
新メンバーが加入時の導入手順を記載しておく。

**Comment by youknowcast** [comment]
僕はこれ見ながら 1.16.1 に読み替えてやりました！
https://qiita.com/hapoon/items/66c96dff36f952e2f899

一部( `.zshrc` に `eval "$(anyenv init -)"` 追加する箇所はコマンドに支持されたとおりに手で実施) 以外は，すんなりいきましたのでポインタだけしておけばよいのかなぁ，と思いますー

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
