### ISSUE TITLE
外部入力(Request, Message など)の Validator がほしい

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#23]
Request の参照や Entity 構造体にデータを詰めたものを Validate() してくれる共通的な仕組みがほしいです．

echo#Validator 使えばよさそうですが，サンプルコード見た感じ， echo インスタンスに直接 Validator を食わせてるようなのでこれはどういうものだろう？ と思っています．
https://echo.labstack.com/guide/request

他によさげな実装があればそちらでも・・

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
