### ISSUE TITLE
DBConnection 周りのモジュール実装がほしい

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#24]
GORM を採用するとして(ここの段階から要検討かもしれませんが・・)，
DBConnection 的なものをどう管理するのがよいか，サンプルに追加を検討いただけますでしょうか．

軽くぐぐって見た感じ，毎回 Open() して defer Close() するみたいなコードしか出てこないのですが，こういうもの・・・？

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
