### ISSUE TITLE
環境変数切り替えの仕組みがほしい

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#25]
node でいう `process.env.XXXX` 的なもので，dev, staging, prod の切り替え等を行いたいです．

外部ライブラリもしくは自前で yaml or toml 読み込んで unmarshal 等は問いませんが，
任意のファイル( `config.go` とか)で読み込んだら，ほかは import するだけで利用できるといった作りだと使いやすそうです．

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
