### ISSUE TITLE
routing を main.go から分離しては？

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#4]
#  背景

今後，routing のテーブルが増えてきたときに，main.go の `route()` 関数にまとめて記載されているのは可読性を損なうおそれがある．

#  目的 

ある程度煩雑な routing を見通しよく書きたい．

#  得られるもの

#  完了の定義

TBD

#  実装案

route.go を新設し，routing まわりについてまとめてできるようにする．

#  懸念点

- 関数移すだけならさして意味がないような気もする・・
  - CoC 的に，暗黙のうちに routing table を作成するといった黒魔術プログラミングはしない方針だと思うので，なおさら・・

#  外部リンク

**Comment by hapoon** [comment]
ここは分離していこうと思ってたところなので、現状は `route.go` でルーティングを管理するようにしますかー 🤔 
(route.goの規模が小さいうちは単体ファイルで、増えて大きなファイルになるようであれば `route` ディレクトリ配下にそれぞれのAPIリソース単位で分けるとか必要かもしれないですねー

**Comment by hapoon** [comment]
後々routerが複雑化するの容易に想像できたのでディレクトリ作成してroute.go設置することにしました。
https://github.com/hapoon/go-api-template/blob/main/route/route.go

**Comment by youknowcast** [comment]
LGTM！

ところで，今後，以下のような感じでハンドラもファイル分けたいなぁってなったら `route` 配下か，それとも別途 `api` とか `controller` とかディレクトリ切る感じになりますか？
それとも，controller 処理については極力，routing と一緒に書くことを推奨します？ 

```
s.POST("/", func(c echo.Context) error api.v1PostHandler)
```

**Comment by hapoon** [comment]
> LGTM！
> 
> ところで，今後，以下のような感じでハンドラもファイル分けたいなぁってなったら `route` 配下か，それとも別途 `api` とか `controller` とかディレクトリ切る感じになりますか？
> それとも，controller 処理については極力，routing と一緒に書くことを推奨します？
> 
> ```
> s.POST("/", func(c echo.Context) error api.v1PostHandler)
> ```

ハンドラーはサービス層かなと思っていて、そこをユースケースを実現するアプリケーションサービスとドメインサービスを分けるとかかなーとも思ってます。
route配下はあくまでもルーティングだけを制御し、バージョン管理(v1,v2...)とRESTful APIのリソース単位で分ける感じで `api` は別途作らないつもりでいます。
