### ISSUE TITLE
request の検証を行うための middleware がほしい

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#5]
#  背景

以下のような用途が想定されている．
- request ヘッダに挿入される JWT トークンの検証
- request ヘッダに挿入される EP を叩くクライアントのメタデータの検証

#  目的 

どのリクエストでも横断的に必要となってくるため，middleware として実装したほうがよい？

#  得られるもの

#  完了の定義

TBD

#  実装案

#  懸念点

#  外部リンク

https://echo.labstack.com/cookbook/middleware
https://medium.com/veltra-engineering/echo-middleware-in-golang-90e1d301eb27

**Comment by youknowcast** [comment]
> request ヘッダに挿入される EP を叩くクライアントのメタデータの検証

こっちはわかりにくいですが， #23 の実装イメージです

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
