### ISSUE TITLE
DB migration 機能がほしい

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#6]
DB アクセスに付随して，以下の機能について検討するのはいかがでしょうか．

- migration 機能
  - DDL の履歴管理，一括作成，削除など
- fixture 機能(テストデータ追加)
  - DB 前提のテストを実施する場合
- seeds 機能(マスタ投入)

別 Prj として migration 検討する場合はそちらで検討できればと．

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
