### ISSUE TITLE
監査ログ取得機能がほしい

### ISSUE THREAD

**Issue by youknowcast** [hapoon/go-api-template#7]
#  背景

Audit log 取得要望に応えられるような仕組みを検討する．

#  目的 

なるべくビジネスロジックとは独立したかたちで，監査用のログ取得できる機構を整備し，
API 基盤標準の機能として利用できるようにしたい．

#  得られるもの

#  完了の定義

TBD

#  実装案

以下の 2 案が考えられる．
- request 時のログ取得
- service 層以下でコミット時に取得
  - 前回データとの差分取得が必要ならこっち？

#  懸念点

以下の観点で設計が必要．
- プライバシーポリシー
- パフォーマンス

#  外部リンク

**Comment by hapoon** [comment]
個別プロジェクトで実行すべきかと判断した為、クローズ
